# Dataset parameters
data_dir: ../inaturalist_12K
max_drifted: 1000
batch_size: 32
min_drifted: 10

# Training parameters
epochs: 1
learning_rate: 0.001
freeze_strategy: upto_stage_3
dropout_rate: 0.5

# Experiment tracking
mlflow_experiment_name: resnet_drift_retraining

# Database update flag
update_db_status: true