global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'biosight'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 5s
    scrape_timeout: 4s