stages:
  prepare_data:
    cmd: >
      python -m prepare_retrain_data 
      --data-dir ${data_dir} 
      --max-drifted ${max_drifted} 
      --batch-size ${batch_size} 
      --generate-stats
      --save-datasets prepared_datasets.pkl
    deps:
      - prepare_retrain_data.py
      - ${data_dir:../inaturalist_12K}
    params:
      - data_dir
      - max_drifted
      - batch_size
    outs:
      - prepared_data_stats.json:
          cache: false
      - prepared_datasets.pkl:
          cache: true

  train:
    cmd: >
      python -m retrain
      --load-datasets prepared_datasets.pkl
      --epochs ${epochs}
      --learning-rate ${learning_rate}
      --freeze-strategy ${freeze_strategy}
      --dropout-rate ${dropout_rate}
      --experiment-name ${mlflow_experiment_name}
    deps:
      - retrain.py
      - prepared_datasets.pkl
    params:
      - epochs
      - learning_rate
      - freeze_strategy
      - dropout_rate
      - mlflow_experiment_name
    outs:
      - best_model_resnet.pth

  evaluate:
    cmd: >
      python -m test_model
      --model-path best_model_resnet.pth
      --load-datasets prepared_datasets.pkl
      --num-classes 10
      --dropout-rate ${dropout_rate}
      --experiment-name ${mlflow_experiment_name}_eval
    deps:
      - test_model.py
      - prepared_datasets.pkl
      - best_model_resnet.pth
    params:
      - dropout_rate
      - mlflow_experiment_name